#!/usr/bin/env bash
# Write web/.env.hosted.local from the linked Supabase CLI project.
# Secrets are written to the gitignored file only; nothing is printed.
#
# Requires one of:
#   - SELECTION_ROOM_DATABASE_URL (full pooler URL with password)
#   - SUPABASE_DB_PASSWORD (database password from Supabase Dashboard)
#
# Get/reset password: Dashboard → Project → Connect → Database password
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT/web/.env.hosted.local"
REF_FILE="$ROOT/supabase/.temp/project-ref"
POOLER_FILE="$ROOT/supabase/.temp/pooler-url"

if [[ ! -f "$REF_FILE" || ! -f "$POOLER_FILE" ]]; then
  echo "Missing supabase link. Run: supabase link --project-ref tucqckdwtbrgmqlnwfhj" >&2
  exit 1
fi

PROJECT_REF="$(tr -d '[:space:]' < "$REF_FILE")"
POOLER_TEMPLATE="$(tr -d '[:space:]' < "$POOLER_FILE")"
SERVICE_ROLE="$(
  supabase projects api-keys --project-ref "$PROJECT_REF" -o json \
    | node -e "const k=JSON.parse(require('fs').readFileSync(0,'utf8')); const row=k.find(x=>x.name==='service_role'); if(!row) process.exit(1); process.stdout.write(row.api_key)"
)"
ANON_KEY="$(
  supabase projects api-keys --project-ref "$PROJECT_REF" -o json \
    | node -e "const k=JSON.parse(require('fs').readFileSync(0,'utf8')); const row=k.find(x=>x.name==='anon'); if(!row) process.exit(1); process.stdout.write(row.api_key)"
)"

if [[ -n "${SELECTION_ROOM_DATABASE_URL:-}" ]]; then
  DATABASE_URL="$SELECTION_ROOM_DATABASE_URL"
elif [[ -n "${SUPABASE_DB_PASSWORD:-}" ]]; then
  DATABASE_URL="$(
    node -e "
      const template = process.argv[1];
      const password = encodeURIComponent(process.argv[2]);
      const u = new URL(template);
      u.password = decodeURIComponent(password);
      u.port = '6543';
      process.stdout.write(u.toString());
    " "$POOLER_TEMPLATE" "$SUPABASE_DB_PASSWORD"
  )"
else
  echo "Set SUPABASE_DB_PASSWORD or SELECTION_ROOM_DATABASE_URL before bootstrap." >&2
  echo "Dashboard → selection-room-hosted → Connect → Database → reset/copy password." >&2
  exit 1
fi

BETA_CODES="${SELECTION_ROOM_BETA_RUN_CODES:-hosted-smoke-test}"
PORT="${HOSTED_SMOKE_PORT:-3099}"
SITE_URL="${NEXT_PUBLIC_SITE_URL:-http://localhost:${PORT}}"

read_preserved_env() {
  local key="$1"
  if [[ -n "${!key:-}" ]]; then
    printf '%s' "${!key}"
    return
  fi
  if [[ -f "$ENV_FILE" ]]; then
    node -e "
      const fs = require('fs');
      const key = process.argv[1];
      const file = process.argv[2];
      for (const line of fs.readFileSync(file, 'utf8').split('\n')) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('#')) continue;
        const eq = trimmed.indexOf('=');
        if (eq === -1) continue;
        if (trimmed.slice(0, eq).trim() === key) {
          process.stdout.write(trimmed.slice(eq + 1).trim());
          process.exit(0);
        }
      }
    " "$key" "$ENV_FILE"
  fi
}

TRIGGER_SECRET_KEY_VALUE="$(read_preserved_env TRIGGER_SECRET_KEY)"
TRIGGER_PROJECT_REF_VALUE="$(read_preserved_env TRIGGER_PROJECT_REF)"
CFBD_API_KEY_VALUE="$(read_preserved_env CFBD_API_KEY)"

if [[ -z "$TRIGGER_PROJECT_REF_VALUE" && -f "$ROOT/web/trigger-project.ts" ]]; then
  TRIGGER_PROJECT_REF_VALUE="$(
    node -e "
      const fs = require('fs');
      const text = fs.readFileSync(process.argv[1], 'utf8');
      const match = text.match(/TRIGGER_PROJECT_REF = \"(proj_[^\"]+)\"/);
      if (match) process.stdout.write(match[1]);
    " "$ROOT/web/trigger-project.ts"
  )"
fi

cat > "$ENV_FILE" <<EOF
# Generated by scripts/bootstrap-hosted-env.sh — gitignored, do not commit
SELECTION_ROOM_RUNTIME=hosted
SELECTION_ROOM_ARTIFACT_STORE=supabase
SELECTION_ROOM_DATABASE_URL=${DATABASE_URL}
SUPABASE_URL=https://${PROJECT_REF}.supabase.co
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE}
SUPABASE_STORAGE_BUCKET=artifacts
# Public client config for the sign-in gate (not secret; ships in the bundle):
NEXT_PUBLIC_SUPABASE_URL=https://${PROJECT_REF}.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
SELECTION_ROOM_HOSTED_EXECUTOR=trigger
SELECTION_ROOM_HOSTED_DAILY_JOB_CAP=10
SELECTION_ROOM_HOSTED_MAX_CONCURRENT=1
SELECTION_ROOM_HOSTED_USER_DAILY_JOB_CAP=5
SELECTION_ROOM_BETA_RUN_CODES=${BETA_CODES}
NEXT_PUBLIC_SITE_URL=${SITE_URL}
# Local worker paths (do not sync to Trigger — cloud uses /app and /opt/venv/bin/python):
# SELECTION_ROOM_REPO_DIR=${ROOT}
# SELECTION_ROOM_PYTHON=${ROOT}/.venv/bin/python
EOF

if [[ -n "$TRIGGER_SECRET_KEY_VALUE" ]]; then
  printf 'TRIGGER_SECRET_KEY=%s\n' "$TRIGGER_SECRET_KEY_VALUE" >> "$ENV_FILE"
fi
if [[ -n "$TRIGGER_PROJECT_REF_VALUE" ]]; then
  printf 'TRIGGER_PROJECT_REF=%s\n' "$TRIGGER_PROJECT_REF_VALUE" >> "$ENV_FILE"
fi
if [[ -n "$CFBD_API_KEY_VALUE" ]]; then
  printf 'CFBD_API_KEY=%s\n' "$CFBD_API_KEY_VALUE" >> "$ENV_FILE"
fi

if [[ -z "$TRIGGER_SECRET_KEY_VALUE" ]]; then
  cat >> "$ENV_FILE" <<'EOF'
# Optional — add before smoke/deploy:
# TRIGGER_SECRET_KEY=
# CFBD_API_KEY=
EOF
fi

echo "Wrote web/.env.hosted.local (secrets not printed)"
