#!/usr/bin/env bash
# Write web/.env.hosted.local from the linked Supabase CLI project.
# Secrets are written to the gitignored file only; nothing is printed.
#
# Requires one of:
#   - SELECTION_ROOM_DATABASE_URL (full pooler URL with password)
#   - SUPABASE_DB_PASSWORD (database password from Supabase Dashboard)
#
# Get/reset password: Dashboard → Project → Connect → Database password
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT/web/.env.hosted.local"
REF_FILE="$ROOT/supabase/.temp/project-ref"
POOLER_FILE="$ROOT/supabase/.temp/pooler-url"

if [[ ! -f "$REF_FILE" || ! -f "$POOLER_FILE" ]]; then
  echo "Missing supabase link. Run: supabase link --project-ref tucqckdwtbrgmqlnwfhj" >&2
  exit 1
fi

PROJECT_REF="$(tr -d '[:space:]' < "$REF_FILE")"
POOLER_TEMPLATE="$(tr -d '[:space:]' < "$POOLER_FILE")"
SERVICE_ROLE="$(
  supabase projects api-keys --project-ref "$PROJECT_REF" -o json \
    | node -e "const k=JSON.parse(require('fs').readFileSync(0,'utf8')); const row=k.find(x=>x.name==='service_role'); if(!row) process.exit(1); process.stdout.write(row.api_key)"
)"

if [[ -n "${SELECTION_ROOM_DATABASE_URL:-}" ]]; then
  DATABASE_URL="$SELECTION_ROOM_DATABASE_URL"
elif [[ -n "${SUPABASE_DB_PASSWORD:-}" ]]; then
  DATABASE_URL="$(
    node -e "
      const template = process.argv[1];
      const password = encodeURIComponent(process.argv[2]);
      const u = new URL(template);
      u.password = decodeURIComponent(password);
      u.port = '6543';
      process.stdout.write(u.toString());
    " "$POOLER_TEMPLATE" "$SUPABASE_DB_PASSWORD"
  )"
else
  echo "Set SUPABASE_DB_PASSWORD or SELECTION_ROOM_DATABASE_URL before bootstrap." >&2
  echo "Dashboard → selection-room-hosted → Connect → Database → reset/copy password." >&2
  exit 1
fi

BETA_CODES="${SELECTION_ROOM_BETA_RUN_CODES:-hosted-smoke-test}"
PORT="${HOSTED_SMOKE_PORT:-3099}"
SITE_URL="${NEXT_PUBLIC_SITE_URL:-http://localhost:${PORT}}"

cat > "$ENV_FILE" <<EOF
# Generated by scripts/bootstrap-hosted-env.sh — gitignored, do not commit
SELECTION_ROOM_RUNTIME=hosted
SELECTION_ROOM_ARTIFACT_STORE=supabase
SELECTION_ROOM_DATABASE_URL=${DATABASE_URL}
SUPABASE_URL=https://${PROJECT_REF}.supabase.co
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE}
SUPABASE_STORAGE_BUCKET=artifacts
SELECTION_ROOM_HOSTED_EXECUTOR=trigger
SELECTION_ROOM_HOSTED_DAILY_JOB_CAP=10
SELECTION_ROOM_HOSTED_MAX_CONCURRENT=1
SELECTION_ROOM_BETA_RUN_CODES=${BETA_CODES}
NEXT_PUBLIC_SITE_URL=${SITE_URL}
SELECTION_ROOM_REPO_DIR=${ROOT}
SELECTION_ROOM_PYTHON=${ROOT}/.venv/bin/python
# Optional — set locally before bootstrap or edit this file:
# TRIGGER_SECRET_KEY=
# TRIGGER_PROJECT_REF=
# CFBD_API_KEY=
EOF

echo "Wrote web/.env.hosted.local (secrets not printed)"
